spring:
  application:
    name: AskItEntityService

  datasource:
    url: jdbc:mysql://localhost:3306/AskItDataBase
    username: root
    password: Rrs@mysql7661

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        enable_lazy_load_no_trans: true
